- name: Install Apache from an MSI 
  hosts: all 
 
  tasks:
  - name: copy chrome binary
    win_copy:
      src: /tmp/GoogleChromeStandaloneEnterprise64.msi
      dest: C:\Windows\TEMP\chrome.msi
        
  - name: Install chrome
    win_package: 
      path: 'C:\Windows\TEMP\chrome.msi'
      state: present
